// Auto-generated category data
const allCategories = [
  {
    id: '小作文词伙一',
    name: '小作文词伙一',
    icon: '📊',
    group: '小作文',
    vocab: [
      { zh: '略微高于平均值', en: 'be slightly above the average' },
      { zh: '平稳地爬升', en: 'climb steadily/solidly' },
      { zh: '波动式爬升', en: 'climb up with fluctuations' },
      { zh: '持续上涨', en: 'continue to increase /soar' },
      { zh: '呈现持续的增长', en: 'display a continuous growth' },
      { zh: '从 38 稳定增长到 61', en: 'grow steadily from 38 to 61' },
      { zh: '在数值上呈现增长', en: 'illustrate an increase in a number' },
      { zh: '更快的增长', en: 'increase more rapidly' },
      { zh: '呈现一个大幅的增长', en: 'present a significant increase' },
      { zh: '匀速地增长', en: 'increase uniformly' },
      { zh: '急剧地下降', en: 'a dramatic decrease' },
      { zh: '一个快速的降幅', en: 'a drastic decrement' },
      { zh: '过去十年里一个轻微的下降', en: 'a modest dip/drop over the last decade' },
      { zh: '除了一次下跌以外', en: 'apart from a slump' },
      { zh: '预计会下降', en: 'be expected to fall steadily' },
      { zh: '继续保持下降', en: 'continue to decline' },
      { zh: '逐渐地从10%下降到 7%', en: 'decline gradually from 10% to 7%' },
      { zh: '明显地下降', en: 'decline noticeably' },
      { zh: '下降得越来越快', en: 'decrease more rapidly' },
      { zh: '尽管下降到1995年水平', en: 'despite a drop to 1995 level' },
    ],
  },
  {
    id: '小作文词伙二',
    name: '小作文词伙二',
    icon: '📉',
    group: '小作文',
    vocab: [
      { zh: '降到仅仅2.5%', en: 'dip/drop to only 2.5%' },
      { zh: '呈现轻微的下降', en: 'display a slight decrease' },
      { zh: '保持稳定', en: 'remain stable/steady' },
      { zh: '保持不变', en: 'stay unchanged' },
      { zh: '保持大概不变', en: 'remain roughly constant' },
      { zh: '在整个期间保持稳定', en: 'remain steady throughout the period' },
      { zh: '保持相同的水平', en: 'maintain the same level' },
      { zh: '达到 94%的峰值不变', en: 'reach a plateau at 94%' },
      { zh: '保持大致的不变的', en: 'remain roughly static' },
      { zh: '停滞了几乎十年', en: 'stagnated for nearly a decade' },
      { zh: '自从2000年以后稳定在19%', en: 'stabilize at 19% since 2000' },
      { zh: '预计会保持这个水平', en: 'be expected to maintain this level' },
      { zh: '伴随着波动下降', en: 'decrease with fluctuations' },
      { zh: '尽管最初有些波动', en: 'despite some initial fluctuations' },
      { zh: '降到34%的最低点', en: 'drop to its bottom at 34%' },
      { zh: '在 8000 位置上下波动', en: 'fluctuate around 8 thousand' },
      { zh: '微幅地波动', en: 'fluctuate moderately' },
      { zh: '在十年内波动式上升', en: 'fluctuate upwardly within a decade' },
      { zh: '增长的最大', en: 'have the biggest increase' },
      { zh: '在1995 年达到峰值 200 亿', en: 'peak at 2 billion in 1995' },
    ],
  },
  {
    id: '小作文词伙三',
    name: '小作文词伙三',
    icon: '📈',
    group: '小作文',
    vocab: [
      { zh: '占了学校预算的 25%', en: 'represent 25% of the school budget' },
      { zh: '增长超过八倍', en: 'rise more than eight fold' },
      { zh: '女性是男性的两倍', en: 'twice as many women as men' },
      { zh: '是2015 年的两倍尺寸大', en: 'be twice the size of it was in 2015' },
      { zh: '一个池子在东北角', en: 'a pond in the northeast corner' },
      { zh: '沿着街道南边', en: 'along the south side of the street' },
      { zh: '围绕着小镇中心', en: 'around the town centre' },
      { zh: '在最初的阶段', en: 'at the initial stage' },
      { zh: '附加在紧挨着旅馆旁边', en: 'be added next to the hotel' },
      { zh: '被森林环绕', en: 'be circled by forests' },
      { zh: '紧挨在购物中心旁', en: 'be located on the shopping mall' },
      { zh: '在马路的对面', en: 'be on the opposite side of the road' },
      { zh: '经历三个不同的阶段', en: 'pass through three distinct stages' },
      { zh: '在最后的阶段', en: 'in the final phase/stage' },
      { zh: '在这个流程的第一阶段', en: 'at the first stage in the process' },
      { zh: '被整修成室内区域', en: 'be modified into an indoor area' },
      { zh: '被并列放置在了体育馆的左边(不接触)', en: 'be juxtaposed to the left of the gym' },
      { zh: '入口处的重新安置', en: 'the relocation of the entrance' },
      { zh: '被传送到一个地方进行混合', en: 'be transferred to a place to be mixed' },
      { zh: '把容器颠倒过来', en: 'turn the container upside down' },
    ],
  },
  {
    id: '暴力犯罪类',
    name: '暴力犯罪类',
    icon: '⚖️',
    group: '大作文',
    vocab: [
      { zh: '被绳之以法', en: 'be brought to justice' },
      { zh: '被认为是个威胁', en: 'be identified as a threat' },
      { zh: '违反法律', en: 'break laws' },
      { zh: '性格缺陷', en: 'character flaw' },
      { zh: '连带损伤', en: 'collateral damage' },
      { zh: '犯下严重的侵犯(罪)', en: 'commit serious offences' },
      { zh: '抑制犯罪', en: 'curb crime / deter crime' },
      { zh: '减少犯罪倾向', en: 'diminish criminal propensity' },
      { zh: '辨别是非', en: 'discriminate between right and wrong' },
      { zh: '危害社会稳定和安全', en: 'endanger social stability and safety' },
      { zh: '逃避惩罚', en: 'escape punishment' },
      { zh: '有震慑作用', en: 'have deterrent effect' },
      { zh: '憎恨社会', en: 'hold a grudge against society' },
      { zh: '侵犯隐私', en: 'intrusion of privacy' },
      { zh: '侵犯了..的隐私', en: 'invade one\'s privacy' },
      { zh: '青少年犯罪', en: 'juvenile delinquency' },
      { zh: '青少年罪犯', en: 'juvenile offenders' },
      { zh: '少年教养院', en: 'juvenile reformatory' },
      { zh: '守法的公民', en: 'law-abiding citizens' },
      { zh: '执法部门', en: 'law enforcement agencies' },
    ],
  },
  {
    id: '家庭旅游类',
    name: '家庭旅游类',
    icon: '✈️',
    group: '大作文',
    vocab: [
      { zh: '满足他们的一些需求', en: 'address some of their needs' },
      { zh: '承担责任', en: 'assume the responsibility' },
      { zh: '平衡工作和生活', en: 'balance work and life' },
      { zh: '忙于家务', en: 'be swamped by household chores' },
      { zh: '被家务事拖累', en: 'be tied down to household chores' },
      { zh: '忙于他们的工作', en: 'bury themselves in work' },
      { zh: '车辆租赁公司', en: 'car rental company' },
      { zh: '生活成本', en: 'cost of living' },
      { zh: '导致人与人疏远', en: 'create alienation between people' },
      { zh: '可支配收入', en: 'disposable income' },
      { zh: '家务活', en: 'domestic chores' },
      { zh: '家庭暴力', en: 'domestic violence' },
      { zh: '促进旅游业的发展', en: 'facilitate the development of tourism' },
      { zh: '家庭归属感', en: 'family attachment' },
      { zh: '经济困难的家庭', en: 'financial-disadvantaged families' },
      { zh: '有好的生活质量', en: 'have a reasonable quality of life' },
      { zh: '家庭杂务', en: 'household chores' },
      { zh: '提高生活标准', en: 'improve living standards' },
      { zh: '保持低调', en: 'keep a low profile' },
      { zh: '过着充实的生活', en: 'lead a fulfilling life' },
    ],
  },
  {
    id: '健康饮食类',
    name: '健康饮食类',
    icon: '🥗',
    group: '大作文',
    vocab: [
      { zh: '更好的生活质量', en: 'a better quality of life' },
      { zh: '采取健康的生活方式', en: 'adopt a healthy lifestyle' },
      { zh: '缓解粮食短缺', en: 'alleviate food shortage' },
      { zh: '对人们的健康有害', en: 'be harmful to human health' },
      { zh: '产生严重的健康问题', en: 'cause serious health problems' },
      { zh: '导致与压力相关的疾病', en: 'cause stress-related illness' },
      { zh: '转基因食品', en: 'genetically modified food' },
      { zh: '提高人们的生活水平', en: 'improve people\'s living standards' },
      { zh: '危害人类的健康', en: 'jeopardize human health' },
      { zh: '过着健康的生活', en: 'lead a healthy life' },
      { zh: '长期的副作用', en: 'long-term side effects' },
      { zh: '增加慢性疾病的患病率', en: 'increase the incidence of chronic illnesses' },
      { zh: '健康的饮食', en: 'a wholesome diet' },
      { zh: '提倡素食', en: 'advocate vegetarian diet' },
      { zh: '不健康的饮食', en: 'an unhealthy diet' },
      { zh: '是罪魁祸首', en: 'be the main culprit' },
      { zh: '不愿意戒烟', en: 'be unwilling to cease smoking' },
      { zh: '增强免疫力', en: 'boost the immune system' },
      { zh: '碳酸饮料', en: 'carbonated drinks' },
      { zh: '慢性疾病', en: 'chronic illnesses' },
    ],
  },
  {
    id: '媒体广告类',
    name: '媒体广告类',
    icon: '📺',
    group: '大作文',
    vocab: [
      { zh: '快速发展的产业', en: 'a fast-developing industry' },
      { zh: '真人秀节目', en: 'a reality TV program' },
      { zh: '针对儿童的广告宣传', en: 'advertisements aimed at children' },
      { zh: '被广告吸引', en: 'be intrigued by the advertisement' },
      { zh: '非常的昂贵', en: 'be prohibitively expensive' },
      { zh: '易受媒体的影响', en: 'be subjected to the influence of the media' },
      { zh: '冲动性购买产品', en: 'buy products on impulse' },
      { zh: '心血来潮买东西', en: 'buy something on a whim' },
      { zh: '代言一个体育服装品牌', en: 'endorse a brand of sportswear' },
      { zh: '代言一个指定的产品', en: 'endorse a particular brand' },
      { zh: '掩盖政治丑闻', en: 'cover up political scandals' },
      { zh: '刺激购买冲动', en: 'evoke impulsive buying' },
      { zh: '送货到家', en: 'have things delivered to their homes' },
      { zh: '高水平的媒体曝光', en: 'high level of media coverage' },
      { zh: '实施一定程度的审查', en: 'impose a degree of censorship' },
      { zh: '公益广告', en: 'non-profit advertisement' },
      { zh: '过度包装的商品', en: 'over-packaged products' },
      { zh: '黄金时段电视', en: 'prime-time television' },
      { zh: '娱乐业', en: 'show business' },
      { zh: '视觉享受', en: 'visual enjoyment' },
    ],
  },
  {
    id: '能源环保类',
    name: '能源环保类',
    icon: '🌱',
    group: '大作文',
    vocab: [
      { zh: '以(牺牲)环境为代价', en: 'at the expense of the environment' },
      { zh: '禁止燃烧化石燃料', en: 'ban the burning of fossil fuels' },
      { zh: '对土壤退化视而不见', en: 'be blind to land degradation' },
      { zh: '对保护环境重要', en: 'be crucial to protecting the environment' },
      { zh: '对环境友好的', en: 'be environmentally friendly' },
      { zh: '有环境意识的', en: 'be environmentally conscious' },
      { zh: '破坏生态平衡', en: 'break ecological balance' },
      { zh: '造成不可逆转的损失', en: 'cause irreversible damage' },
      { zh: '构成了潜在的风险', en: 'constitute a potential risk' },
      { zh: '创造一个有利的环境', en: 'create a favorable condition' },
      { zh: '产生废气', en: 'create exhaust fumes' },
      { zh: '毁坏野生动物栖息地', en: 'destroy wildlife habitats' },
      { zh: '对生态系统产生深远的影响', en: 'exert a far-reaching impact on ecology' },
      { zh: '过渡地开采大自然', en: 'exploit the nature excessively' },
      { zh: '极端天气情况', en: 'extreme weather conditions' },
      { zh: '全球变暖', en: 'global warming' },
      { zh: '提高土地生产率', en: 'improve land productivity' },
      { zh: '导致..的迅速枯竭', en: 'lead to the rapid depletion of…' },
      { zh: '维持生态平衡', en: 'maintain the ecological balance' },
      { zh: '做出短期的牺牲', en: 'make the short-term sacrifice' },
    ],
  },
  {
    id: '品格教育类',
    name: '品格教育类',
    icon: '🎓',
    group: '大作文',
    vocab: [
      { zh: '一种虐待的方式', en: 'a form of abuse' },
      { zh: '名牌大学', en: 'a prestigious university' },
      { zh: '在整个学校教育体系里', en: 'throughout the schooling system' },
      { zh: '放弃物质的追求', en: 'abandon the pursuit of materialism' },
      { zh: '改掉这一恶习', en: 'abandon the vile habit' },
      { zh: '学术能力', en: 'academic capabilities' },
      { zh: '学业优异的学生', en: 'academically advantaged students' },
      { zh: '发挥某人的潜力', en: 'achieve one\'s potential' },
      { zh: '适应未来的挑战', en: 'adapt to future challenges' },
      { zh: '承担教育花费', en: 'afford educational expenses' },
      { zh: '一个空头的承诺', en: 'an empty promise' },
      { zh: '重视教育背景', en: 'attach importance to education background' },
      { zh: '参加补习班', en: 'attend \'cram schools\'' },
      { zh: '避免拖延', en: 'avoid procrastination' },
      { zh: '从伦理上说是错误的/理论上说是错误的', en: 'be ethically wrong / theoretically wrong' },
      { zh: '遵从父母的意愿', en: 'be obedient to parents \'expectations' },
      { zh: '对学生带来巨大的好处', en: 'be of immense benefit to students' },
      { zh: '叛逆的', en: 'be rebellious' },
      { zh: '对他们的行为负责', en: 'be responsible for what they do' },
      { zh: '易受不良的影响', en: 'be vulnerable to negative influence' },
    ],
  },
  {
    id: '人文历史类',
    name: '人文历史类',
    icon: '🏛️',
    group: '大作文',
    vocab: [
      { zh: '全球性的语言', en: 'a global language' },
      { zh: '归属感', en: 'a sense of belonging' },
      { zh: '认同感', en: 'a sense of identity' },
      { zh: '习得一门外语', en: 'acquire a foreign language' },
      { zh: '建筑的风格', en: 'architectural styles' },
      { zh: '有经济和文化价值', en: 'be of commercial and cultural values' },
      { zh: '文化同化', en: 'cultural assimilation' },
      { zh: '文化退化', en: 'cultural devolution' },
      { zh: '文化多样性', en: 'cultural diversity' },
      { zh: '文化遗产', en: 'cultural heritage' },
      { zh: '文化身份', en: 'cultural identity' },
      { zh: '文化或历史景点', en: 'cultural or historical attractions' },
      { zh: '文化禁忌', en: 'cultural taboo' },
      { zh: '文化同一性', en: 'cultural uniformity' },
      { zh: '消除偏见和敌意', en: 'dispel prejudice and hostility' },
      { zh: '接受不同文化和价值观', en: 'embrace different cultures and values' },
      { zh: '濒临消失的语言', en: 'endangered language' },
      { zh: '表达个人品味和身份', en: 'express individual taste and identity' },
      { zh: '一直成为禁忌', en: 'have been a taboo' },
      { zh: '有利益冲突', en: 'have conflicting interests' },
    ],
  },
  {
    id: '商业职场类',
    name: '商业职场类',
    icon: '💼',
    group: '大作文',
    vocab: [
      { zh: '有成就感的事业', en: 'a fulfilling career' },
      { zh: '良好的工作前景', en: 'a good job prospect' },
      { zh: '前景乐观的职业', en: 'a promising career' },
      { zh: '工作的安全感', en: 'a sense of job security' },
      { zh: '失业期', en: 'a spell of unemployment' },
      { zh: '对一些技能精通', en: 'become proficient in some skills' },
      { zh: '职业愿景', en: 'career aspirations' },
      { zh: '职业成就', en: 'career achievement' },
      { zh: '上下班通勤时间', en: 'commuting time' },
      { zh: '竞争的优势', en: 'competitive advantage' },
      { zh: '消费品', en: 'consumer goods /products' },
      { zh: '培养人际关系能力', en: 'develop interpersonal skills' },
      { zh: '性别/年龄歧视', en: 'discriminate on the basis of gender' },
      { zh: '建立亲密的关系', en: 'build a close rapport' },
      { zh: '做出共同的努力', en: 'engage in a concerted effort' },
      { zh: '增加创造力', en: 'enhance creativity' },
      { zh: '增强团队合作', en: 'enhance teamwork spirit' },
      { zh: '建立性别平等', en: 'establish gender equality' },
      { zh: '没有实现工作生活的平衡', en: 'fail to achieve work-life balance' },
      { zh: '在他们工作中感觉安全', en: 'feel secure in their jobs' },
    ],
  },
  {
    id: '网络科技类',
    name: '网络科技类',
    icon: '💻',
    group: '大作文',
    vocab: [
      { zh: '比以前获取更多的信息', en: 'access more information than ever before' },
      { zh: '采用尖端的科技', en: 'adopt cutting-edge technology' },
      { zh: '寻求在线退款复杂而低效', en: 'be cumbersome to seek a refund online' },
      { zh: '可以无限制的上网', en: 'be given unlimited Internet access' },
      { zh: '沉溺于在线游戏', en: 'be addicted to online games' },
      { zh: '被网购快速的取代', en: 'be rapidly giving way to online shopping' },
      { zh: '被看做是一种必须的装备', en: 'be seen as a must-have device' },
      { zh: '不被诱惑干扰', en: 'be undistracted by temptations' },
      { zh: '成为一种耗费时间的诱惑', en: 'be a time-consuming temptation' },
      { zh: '又流行起来', en: 'come back into fashion' },
      { zh: '通过互联网和他人交流', en: 'communicate with others via the Internet' },
      { zh: '包含敏感信息', en: 'contain sensitive information' },
      { zh: '尖端的技术', en: 'cutting-edge technology' },
      { zh: '网络约会', en: 'digital/online dating' },
      { zh: '网络科技的革新', en: 'digital revolution' },
      { zh: '分散他们的注意力', en: 'distract their attention' },
      { zh: '运用最新科技技术', en: 'employ cutting-edge technology' },
      { zh: '没有抵挡住的诱惑', en: 'fail to resist the lure of...' },
      { zh: '政府对互联网的审查', en: 'government censorship of the Internet' },
      { zh: '安装过滤软件', en: 'install filtering software' },
    ],
  },
  {
    id: '政府社会类',
    name: '政府社会类',
    icon: '🏛️',
    group: '大作文',
    vocab: [
      { zh: '预算盈余', en: 'a budget surplus' },
      { zh: '公众对税收政策的强烈反对', en: 'a public backlash against tax policy' },
      { zh: '安全感', en: 'a sense of security' },
      { zh: '流动人口', en: 'a transient population' },
      { zh: '摒弃我们的传统习俗', en: 'abandon our traditional custom' },
      { zh: '积累社会经验', en: 'accumulate social experience' },
      { zh: '适应一个新环境', en: 'adapt to a new environment' },
      { zh: '足够的可支配收入', en: 'adequate disposable income' },
      { zh: '倡导新的生活方式', en: 'advocate the new lifestyle' },
      { zh: '老龄化人群', en: 'the elderly / the senior population' },
      { zh: '社会各个阶层', en: 'all walks of life' },
      { zh: '与现实隔绝', en: 'be detached from reality' },
      { zh: '逐渐得到社会重视', en: 'be increasingly valued by society' },
      { zh: '有更高的社会接受度', en: 'be more socially acceptable' },
      { zh: '成为政府首要任务', en: 'be the government\'s priority' },
      { zh: '处在贫困线以下', en: 'below the poverty line' },
      { zh: '迫于公众压力', en: 'bow to public pressure' },
      { zh: '带来不可估量的经济效益', en: 'bring immeasurable economic benefits' },
    ],
  },
];